import Head from 'next/head'
import Image from 'next/image'
import Header from '@/components/Header'
import imgMainBlog from '../public/assets/complete-design.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header siteAuthor='Lam Nguyen' siteTitle='Lam Nguyen Blog'/>
      <main className='flex items-center justify-between px-10 mx-auto space-y-5 bg-gray-300 rounded max-w-7xl sm:p-10'>        
        <div>
          <h1 className='max-w-xl font-sans text-5xl'>
            <span className='font-serif cursor-pointer'>Lam Nguyen</span> blog
          </h1>
          <h2>Join in, you might be interested!{" "}</h2>
        </div>
        <div className='items-center hidden md:inline-flex'>
          <Image src={imgMainBlog} alt="" />
        </div>
      </main>
    </>
  )
}
